In [1]:
import numpy as np

In [2]:
# Python list
my_list = [1, 2, 3, 4, 5]

# NumPy array
my_array = np.array([1, 2, 3, 4, 5])

In [3]:
# Python list — doubles the list (repeats it)
print(my_list * 2)

# NumPy array — doubles every value
print(my_array * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [4]:
arr = np.array([10, 20, 30, 40, 50])
print(arr + 5)
print(arr ** 2)

[15 25 35 45 55]
[ 100  400  900 1600 2500]


In [7]:
matrix = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])
matrix.shape

(3, 4)

In [ ]:
print(matrix[0])	
print(matrix[0, 2])
print(matrix[:, 1])

[1 2 3 4]
3
[ 2  6 10]


In [9]:
patients = np.array([
    [25, 70, 120, 80],   # patient 1: age, weight, bp_high, bp_low
    [30, 85, 130, 90],   # patient 2
    [45, 60, 110, 75],   # patient 3
])

In [12]:
patients[2, 1]
patients[0]
patients[:, 1] 

array([70, 85, 60])

In [13]:
data = np.array([
    [10, 20, 30],   # student 1 scores
    [40, 50, 60],   # student 2 scores
    [70, 80, 90],   # student 3 scores
])

In [1]:
%pip install flask


   ---------------------------------------- 0/3 [werkzeug]
   ------------- -------------------------- 1/3 [itsdangerous]
   ---------------------------------------- 3/3 [flask]

Note: you may need to restart the kernel to use updated packages.


In [14]:
print(data.sum(axis=0))
print(data.sum(axis=1))

[120 150 180]
[ 60 150 240]


In [16]:
salaries = np.array([50000, 60000, 70000, 55000])

# ❌ Without vectorization — slow loop
for i in range(len(salaries)):
    salaries[i] = salaries[i] * 1.10

# ✅ With vectorization — one line, much faster
salaries = salaries * 1.10
salaries

array([60500., 72600., 84700., 66550.])

In [ ]:
temperatures = [36.5, 38.2, 37.0, 39.1, 36.8]
for i in range(len(temperatures)):
	if temperatures[i] > 38.0:
		print("fever")
	else:
		print("normal")

In [2]:
scores = [45, 82, 61, 39, 75, 90, 55]
for i in scores:
    if i >= 50:
        print("Pass")
    else:
        print("Fail")

Fail
Pass
Pass
Fail
Pass
Pass
Pass


In [4]:
count = 0
for score in scores:
    if score >= 50:
        print(f"{score} → Pass")
        count = count + 1  # add 1 every time we pass
    else:
        print(f"{score} → Fail")

print(f"{count} students passed")

45 → Fail
82 → Pass
61 → Pass
39 → Fail
75 → Pass
90 → Pass
55 → Pass
5 students passed


In [5]:
products = [
	{"name": "Laptop", "price": 999},
	{"name": "Phone",  "price": 699},
	{"name": "Tablet", "price": 449},
]

for product in products:
    if product["price"] > 600:
        print({product['name']})

{'Laptop'}
{'Phone'}


In [6]:
for product in products:
    print(f"{product['name']} cost {product['price']}")

Laptop cost 999
Phone cost 699
Tablet cost 449


In [ ]:
def min_max(data):
    return (min(data), max(data))   # return two values at once

low, high = min_max([4, 7, 2, 9, 1])
print(low)    # → 1
print(high)   # → 9

AttributeError: 'list' object has no attribute 'unique'